# Generated by Django 5.1.5 on 2025-02-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bool',
            new_name='bio',
        ),
    ]
